[package]
name = "rust_interrupts_rtic"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-semihosting = "0.5.0"
panic-semihosting = "0.6.0"
rtic = { version = "2.2.0", features = ["thumbv7-backend"] }
stm32f3xx-hal = { version = "0.10.0", features = ["stm32f303xc"] }

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true

[profile.dev]
panic = "abort"

