[package]
name = "rust_interrupts_pac"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7.5", features = ["set-sp", "set-vtor"] }
critical-section = "1.2.0"
stm32f3 = { version = "0.16.0", features = ["stm32f303"] }
panic-rtt-target = { version="0.1.2", features = ["cortex-m"]}
rtt-target = { version="0.3.1", features = ["cortex-m"]}

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true

[profile.dev]
panic = "abort"

